### ISSUE TITLE
Not able to display multiple documents on same page

### ISSUE THREAD

**Issue by amushate** [stephanrauh/extended-pdf-viewer-showcase#161]
Not able to display multiple pdf files at the same page.

**Comment by stephanrauh** [comment]
Yes, that's true. I'm afraid I can't do something about it. You can try to wrap the PDF viewer in an iFrame. Or you can use https://www.npmjs.com/package/ng2-pdfjs-viewer. That's a PDF viewer doing just that: putting pdf.js in an iFrame.
