### ISSUE TITLE
Not able to print on IE11/Edge

### ISSUE THREAD

**Issue by vnngoc156** [stephanrauh/extended-pdf-viewer-showcase#26]
I clone the source, build, and run locally. Most of the features work great on FF/Chrome/IE11/Edge except that printing doesn't work on IE11/Edge. That happens for both direct printing from viewer toolbar and via print service (in Custom Print Progress and Print API and print range page).

No error outputted in the console log when invoke printing.

**Comment by stephanrauh** [comment]
Oops - typo gremlin has hit again. Thanks for pointing this out!

Please update the local showcase to the latest version. The error should be a matter of the past now. I'll update the showcase itself (https://pdfviewer.net) later this week-end.
