### ISSUE TITLE
Getting errors related to password prompt

### ISSUE THREAD

**Issue by adambeer** [stephanrauh/extended-pdf-viewer-showcase#385]
Im trying to run the showcase using the start2 script and am running into some errors:

Error: src/app/extended-pdf-viewer/passwords/custom-password-prompt.ts:1:10 - error TS2305: Module '"ngx-extended-pdf-viewer"' has no exported member 'PasswordPrompt'.

1 import { PasswordPrompt } from "ngx-extended-pdf-viewer";
~~~~~~~~~~~~~~


Error: src/app/extended-pdf-viewer/passwords/passwords.component.ts:2:62 - error TS2305: Module '"ngx-extended-pdf-viewer"' has no exported member 'PasswordPrompt'.

2 import { IPDFViewerApplication, NgxExtendedPdfViewerService, PasswordPrompt, pdfDefaultOptions } from 'ngx-extended-pdf-viewer';
~~~~~~~~~~~~~~

Error: src/app/extended-pdf-viewer/passwords/passwords.component.ts:31:60 - error TS2339: Property 'passwordPrompt' does not exist on type 'IPDFViewerApplication'.

31         this.originalPasswordPrompt = PDFViewerApplication.passwordPrompt;
 ~~~~~~~~~~~~~~


Error: src/app/extended-pdf-viewer/passwords/passwords.component.ts:33:25 - error TS2339: Property 'passwordPrompt' does not exist on type '{ needsES5: boolean; cursorToolOnLoad: number; defaultUrl: string; defaultZoomValue: any; disableHistory: boolean; disablePageLabels: boolean; enablePrintAutoRotate: boolean; enableWebGL: boolean; ... 38 more ...; defaultCacheSize: number; }'.

33       pdfDefaultOptions.passwordPrompt = new CustomPasswordPrompt();
~~~~~~~~~~~~~~

Error: src/app/extended-pdf-viewer/passwords/passwords.component.ts:34:28 - error TS2339: Property 'passwordPrompt' does not exist on type 'IPDFViewerApplication'.

34       PDFViewerApplication.passwordPrompt = new CustomPasswordPrompt();
~~~~~~~~~~~~~~


Error: src/app/extended-pdf-viewer/passwords/passwords.component.ts:37:27 - error TS2339: Property 'passwordPrompt' does not exist on type '{ needsES5: boolean; cursorToolOnLoad: number; defaultUrl: string; defaultZoomValue: any; disableHistory: boolean; disablePageLabels: boolean; enablePrintAutoRotate: boolean; enableWebGL: boolean; ... 38 more ...; defaultCacheSize: number; }'.

37         pdfDefaultOptions.passwordPrompt = this.originalPasswordPrompt;
~~~~~~~~~~~~~~

Error: src/app/extended-pdf-viewer/passwords/passwords.component.ts:39:30 - error TS2339: Property 'passwordPrompt' does not exist on type 'IPDFViewerApplication'.

39         PDFViewerApplication.passwordPrompt = this.originalPasswordPrompt;

**Comment by stephanrauh** [comment]
I'm currently publishing the next version. Expect the errors to be gone in ten minutes.

**Comment by stephanrauh** [comment]
Please update to version 11.0.3. It contains the missing classes and interfaces.

**Comment by stephanrauh** [comment]
I've just compiled and published the new version of the showcase. I'm positive it works on your machine, too. If it doesn't, don't hesitate to tell me.

Enjoy!
Stephan
