### ISSUE TITLE
Not able to highlight as dark yellow, always coming as light

### ISSUE THREAD

**Issue by vijucalicut** [stephanrauh/extended-pdf-viewer-showcase#49]
![image](https://user-images.githubusercontent.com/19604183/86608552-534ad900-bfc8-11ea-90c8-63c1e8556463.png)

I have highlighted the multi-text, when giving the dark color, By default It is lightening the color. I have given the color code as follows.

 .textLayer .highlight {
      background-color: #ccff00 !important;
  }

Is there any way for doing highlight with fluorescent yellow (#ccff00)?

**Comment by stephanrauh** [comment]
I'm not sure. This behavior already has puzzled me, too. There's a div layer modifying the background color. As far as I remember, it's the textlayer, and it's changing the color by applying an opacity of 50%. But I'm not sure about the details, I just remember the general concept.

I didn't dare to change the opacity (or whatever it was) to 100% for fear of side-effect. When you try it, would you mind to tell me if there are side effects? I'd love to improve that confusing setting in the 4.0 version. :)

Best regards,
Stephan

**Comment by vijucalicut** [comment]
```
.textLayer .highlight.color5.selected {
      background-color: #F8FF04 !important;
    }

    .textLayer {
      opacity: 0.6 !important;
    }
```
@stephanrauh  This is working for me :)
Thank you

**Comment by vijucalicut** [comment]
@stephanrauh  I have a requirement to change the font style and color on the header of our pdf viewer, Could you please suggest the best way for doing that. PFB the section for change.

![image](https://user-images.githubusercontent.com/19604183/87417873-670cc580-c5ee-11ea-9ac3-54feb7994f1a.png)

**Comment by stephanrauh** [comment]
Let's close the ticket. :)
