### ISSUE TITLE
How to change the color of text in the pdf viewer header

### ISSUE THREAD

**Issue by vijucalicut** [stephanrauh/extended-pdf-viewer-showcase#60]
@stephanrauh I have a requirement to change the font style and color on the header of our pdf viewer, Could you please suggest the best way for doing that. PFB the section for change.

![image](https://user-images.githubusercontent.com/19604183/87453121-b15a6a80-c61f-11ea-802e-d66f276b971b.png)

**Comment by stephanrauh** [comment]
There's already a ticket for this, and it's slowly trickling up on my priority list: https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/244

In the meantime, have a look at the CSS rules defined here: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/master/projects/ngx-extended-pdf-viewer/src/lib/viewer-with-images.css

You can override them by custom rules in the `styles.css`. Changing the font style should be easy. Unfortunately, there are lots of CSS rule defining the color and the shadows.

**Comment by stephanrauh** [comment]
Color theming has landed a couple of version ago in ngx-extended-pdf-viewer.
